on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2      
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - run: cd orion_prop_oriented && dune build @doc
